import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <section id="parallax" className="${styles.parallax} hero is-large">
          <div className="hero-body">
            <div className="column is-6 is-offset-6">
              <h1 className="title is-1 has-text-white">Gym Capacity</h1>
              <hr className="content-divider" />
              <h2 className="subtitle has-text-light">Choose your assistance for this week</h2>
              <a href="#" className="button is-white is-inverted">Next <svg className="svg-inline--fa fa-chevron-right fa-w-10" data-prefix="fad" data-icon="chevron-right" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" data-fa-i2svg=""><g class="fa-group"><path class="fa-secondary" fill="currentColor" d="M188.74 256l56.78 56.89L91.21 466.9a24 24 0 0 1-33.94 0l-22.7-22.65a23.93 23.93 0 0 1 0-33.84z"></path><path class="fa-primary" fill="currentColor" d="M91.25 45.06l194.33 194a23.93 23.93 0 0 1 0 33.84l-40 40-211-211.34a23.92 23.92 0 0 1 0-33.84l22.7-22.65a24 24 0 0 1 33.97-.01z"></path></g></svg></a>
            </div>
          </div>
        </section>
        <section>

        </section>
      </main>

      <footer >

      </footer>
    </div>
  )
}
